# Порт сервера
server:
  port: 8082

# Название приложения
spring:
  application:
    name: payment-service

  # Настройка подключения к базе данных H2
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Включение веб-консоли H2
  h2:
    console:
      enabled: true

  # Настройка JPA и Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Настройка OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /


# Настройка Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        slidingWindowSize: 10
        minimumNumberOfCalls: 5  # ← важно: минимум 5 вызовов для анализа
    instances:
      payment: # ← имя из @CircuitBreaker(name = "payment")
        baseConfig: default

  ratelimiter:
    instances:
      createLimiter:
        limitRefreshPeriod: 15s # период обновления лимита
        limitForPeriod: 5 # максимальное число запросов за период
        timeoutDuration: 0s # время ожидания, если лимит превышен

logging:
  level:
    io.github.resilience4j: DEBUG
    ru.v_and_a: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics